// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrcpnywbxjmaorarlqhe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyY3BueXdieGptYW9yYXJscWhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NDk3ODIsImV4cCI6MjA3NDAyNTc4Mn0.-GVl0yCl6PRJcUtnymx1aNc3EEGmGTyzG7oLIG561ag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});